import os
import re
import smtplib
import ssl
import time
from pathlib import Path
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.header import Header
from email.utils import formatdate, make_msgid
from typing import Dict, Any, Optional
import logging

from src.config import AppConfig
from src.post_formatter import FormattedPost

logger = logging.getLogger(__name__)


class WordPressMailSender:
    """
    Sends posts to WordPress and Google Blogger via Email using standard SMTP.
    Supports Jetpack Post by Email, Postie, standard WP mail receivers, and Blogger Post using Email,
    including PNG/JPEG illustration attachments generated by Draw Things.
    """

    def __init__(self, config: AppConfig):
        self.config = config

    @staticmethod
    def _load_lightweight_image(path: Path, max_bytes: int = 120_000):
        """Returns (bytes, mime_subtype). Converts PNG to a small JPEG so the email stays tiny."""
        raw = path.read_bytes()
        try:
            import io
            from PIL import Image
            img = Image.open(io.BytesIO(raw)).convert("RGB")
            for quality in (82, 72, 62, 50):
                buf = io.BytesIO()
                img.save(buf, "JPEG", quality=quality, optimize=True)
                if buf.tell() <= max_bytes:
                    break
            return buf.getvalue(), "jpeg"
        except Exception as e:
            logger.warning(f"Pillow compression unavailable ({e}); attaching original image.")
            return raw, "png"

    @staticmethod
    def _sanitize_html_for_blogger(html_text: str) -> str:
        """
        Simplifies HTML specifically for Blogger's 'Post using email' and strict outbound SMTP filters (e.g., Outlook.com 550 5.7.520):
        1. Replaces <a href="...">text</a> with plain text (eliminates external URL spam-filter triggers while keeping DOI strings intact).
        2. Converts <table> rows into simple <p> lines.
        3. Converts styled blockquote / callout divs into clean <blockquote><p>...</p></blockquote>.
        4. Strips inline style="..." and class="..." attributes so only lightweight semantic tags remain.
        """
        cleaned = html_text
        # 1. Strip <a> tags, keeping inner text (e.g. 'DOI: 10.xxxx/...')
        cleaned = re.sub(r"<a\b[^>]*>(.*?)</a>", r"\1", cleaned, flags=re.IGNORECASE | re.DOTALL)
        # Remove any remaining bare http/https URLs
        cleaned = re.sub(r"https?://(?:dx\.)?doi\.org/(10\.\S+)", r"DOI: \1", cleaned)
        cleaned = re.sub(r"https?://\S+", "", cleaned)

        # 2. Convert <table> blocks into simple paragraphs
        def _table_to_paragraphs(match: re.Match) -> str:
            tbl = match.group(0)
            rows = re.findall(r"<tr\b[^>]*>(.*?)</tr>", tbl, flags=re.IGNORECASE | re.DOTALL)
            p_lines = []
            for row in rows:
                if "<th" in row.lower():
                    continue
                cells = re.findall(r"<td\b[^>]*>(.*?)</td>", row, flags=re.IGNORECASE | re.DOTALL)
                if len(cells) >= 2:
                    k = re.sub(r"<[^>]+>", "", cells[0]).strip()
                    v = cells[1].strip()
                    p_lines.append(f"<p>・<strong>{k}</strong>：{v}</p>")
            return "\n".join(p_lines)

        cleaned = re.sub(r"<table\b[^>]*>.*?</table>", _table_to_paragraphs, cleaned, flags=re.IGNORECASE | re.DOTALL)

        # 3. Replace styled scene divider divs with simple <p>
        cleaned = re.sub(
            r"<div\b[^>]*>\s*(?:✦ ✦ ✦|◆ ◆ ◆)\s*</div>",
            "<p>✦ ✦ ✦</p>",
            cleaned,
            flags=re.IGNORECASE,
        )

        # 4. Convert remaining callout/header <div>...</div> blocks into <p>...</p> and strip outer container divs
        cleaned = re.sub(r"<div\b[^>]*class=[\"']rikejo-novel-container[\"'][^>]*>", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"<div\b[^>]*>(.*?)</div>", r"<p>\1</p>", cleaned, flags=re.IGNORECASE | re.DOTALL)
        cleaned = re.sub(r"</?div\b[^>]*>", "", cleaned, flags=re.IGNORECASE)

        # 5. Strip all inline style="..." and class="..." attributes
        cleaned = re.sub(r'\s+(?:style|class)=["\'][^"\']*["\']', "", cleaned, flags=re.IGNORECASE)

        return cleaned.strip()

    def create_mime_message(
        self,
        post: FormattedPost,
        to_email: Optional[str] = None,
        for_blogger: bool = False,
    ) -> MIMEMultipart:
        has_image = bool(post.image_path and Path(post.image_path).exists())
        # Blogger宛の画像添付は既定で有効。バウンス時は ATTACH_IMAGES_BLOGGER=false で無効化できる
        if has_image and for_blogger and os.environ.get(
            "ATTACH_IMAGES_BLOGGER", "true"
        ).strip().lower() not in ("1", "true", "yes"):
            has_image = False
        if has_image:
            msg = MIMEMultipart("mixed")
            alt_part = MIMEMultipart("alternative")
        else:
            msg = MIMEMultipart("alternative")
            alt_part = msg

        msg["Subject"] = Header(post.title, "utf-8")

        try:
            self.config.from_name.encode("ascii")
            from_display = self.config.from_name
        except UnicodeEncodeError:
            from_display = Header(self.config.from_name, "utf-8").encode()
        msg["From"] = f"{from_display} <{self.config.smtp_user}>"

        recipient = to_email if to_email is not None else (
            self.config.blogger_post_email if for_blogger else self.config.wp_post_email
        )
        msg["To"] = recipient

        msg["Date"] = formatdate(localtime=True)
        domain = self.config.smtp_user.split("@")[-1] if "@" in self.config.smtp_user else "rikejo-science-novel.local"
        msg["Message-ID"] = make_msgid(domain=domain)

        if for_blogger:
            raw_plain = post.content_plain_clean or post.content_plain
            plain_body = re.sub(r"\[([^\]]+)\]\(https?://[^\)]+\)", r"\1", raw_plain)
            plain_body = re.sub(r"https?://(?:dx\.)?doi\.org/(10\.\S+)", r"DOI: \1", plain_body)
            plain_body = re.sub(r"https?://\S+", "", plain_body)
            raw_html = post.content_html_clean or post.content_html
            html_body = self._sanitize_html_for_blogger(raw_html)
        else:
            plain_body = post.content_plain
            html_body = post.content_html

        part_text = MIMEText(plain_body, "plain", "utf-8")
        part_html = MIMEText(html_body, "html", "utf-8")

        alt_part.attach(part_text)
        alt_part.attach(part_html)

        if has_image:
            msg.attach(alt_part)
            img_bytes, subtype = self._load_lightweight_image(Path(post.image_path))
            att_name = f"illustration.{'jpg' if subtype == 'jpeg' else 'png'}"
            img_part = MIMEImage(img_bytes, _subtype=subtype, name=att_name)
            img_part.add_header("Content-Disposition", "attachment", filename=att_name)
            msg.attach(img_part)
            logger.info(f"Attached illustration image: {att_name} ({len(img_bytes)} bytes)")

        return msg

    def _get_blogger_recipients(self) -> list[str]:
        if not self.config.blogger_post_email:
            return []
        return [addr.strip() for addr in self.config.blogger_post_email.split(",") if addr.strip()]

    def _send_single_message(self, recipient: str, msg: MIMEMultipart):
        if self.config.smtp_use_ssl:
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(self.config.smtp_host, self.config.smtp_port, context=context) as server:
                server.login(self.config.smtp_user, self.config.smtp_password)
                server.sendmail(self.config.smtp_user, [recipient], msg.as_string())
        else:
            with smtplib.SMTP(self.config.smtp_host, self.config.smtp_port) as server:
                server.ehlo()
                if self.config.smtp_use_tls:
                    context = ssl.create_default_context()
                    server.starttls(context=context)
                    server.ehlo()
                server.login(self.config.smtp_user, self.config.smtp_password)
                server.sendmail(self.config.smtp_user, [recipient], msg.as_string())

    def send_post(
        self,
        post: FormattedPost,
        dry_run: bool = False,
        blogger_only: bool = False,
    ) -> Dict[str, Any]:
        blogger_recipients = self._get_blogger_recipients()
        wp_recipient = "" if blogger_only else self.config.wp_post_email
        has_image = bool(post.image_path and Path(post.image_path).exists())

        if dry_run or not self.config.smtp_user or (not wp_recipient and not blogger_recipients):
            logger.info("================ [DRY RUN / PREVIEW MODE] ================")
            if not blogger_only:
                logger.info(f"Target WP Email: {self.config.wp_post_email or '(Not Set - WP_POST_EMAIL)'}")
            logger.info(f"Target Blogger Email: {self.config.blogger_post_email or '(Not Set - BLOGGER_POST_EMAIL)'}")
            logger.info(f"Subject (Post Title): {post.title}")
            logger.info(f"From: {self.config.smtp_user or '(Not Set - SMTP_USER)'}")
            logger.info(f"Status: {post.status}")
            logger.info(f"Categories: {', '.join(post.categories)}")
            logger.info(f"Tags: {', '.join(post.tags)}")
            logger.info(f"WP HTML Content Length: {len(post.content_html)} chars")
            logger.info(f"Illustration Attachment: {post.image_path if has_image else '(None)'}")
            logger.info("==========================================================")
            return {
                "success": True,
                "dry_run": True,
                "title": post.title,
                "to": self.config.blogger_post_email if blogger_only else self.config.wp_post_email,
                "blogger_to": blogger_recipients,
                "image_path": post.image_path if has_image else None,
                "message": "Dry run completed successfully. No actual email sent.",
            }

        logger.info(f"Connecting to SMTP server {self.config.smtp_host}:{self.config.smtp_port}...")
        try:
            sent_blogger = []
            if wp_recipient:
                wp_msg = self.create_mime_message(post, to_email=wp_recipient, for_blogger=False)
                self._send_single_message(wp_recipient, wp_msg)
                logger.info(f"Successfully posted to WordPress via email! Recipient: {wp_recipient}")

            for b_addr in blogger_recipients:
                try:
                    if wp_recipient:
                        time.sleep(8)
                    b_msg = self.create_mime_message(post, to_email=b_addr, for_blogger=True)
                    self._send_single_message(b_addr, b_msg)
                    sent_blogger.append(b_addr)
                    logger.info(f"Successfully posted to Blogger via email! Recipient: {b_addr}")
                except Exception as b_err:
                    if blogger_only:
                        raise
                    logger.error(f"Failed to send email to Blogger ({b_addr}): {b_err}", exc_info=True)

            return {
                "success": True,
                "dry_run": False,
                "title": post.title,
                "to": self.config.blogger_post_email if blogger_only else self.config.wp_post_email,
                "blogger_to": sent_blogger,
                "message": f"Post '{post.title}' successfully emailed.",
            }
        except Exception as e:
            logger.error(f"Failed to send email: {e}", exc_info=True)
            return {
                "success": False,
                "dry_run": False,
                "title": post.title,
                "to": self.config.blogger_post_email if blogger_only else self.config.wp_post_email,
                "blogger_to": [],
                "error": str(e),
            }
